### ISSUE TITLE
unexpected keyword argument 'standardize'

### ISSUE THREAD

**Issue by claragici** [ymoslem/MT-Evaluation#1]
Hi, 
corpus-wer.py gets the error 
`Traceback (most recent call last):
  File "/mnt/c/Users/clara.ginovart/Desktop/alocai/corpus-wer.py", line 28, in <module>
    wer_score = wer(refs, preds, standardize=True)    # "standardize" expands abbreviations
TypeError: wer() got an unexpected keyword argument 'standardize'`

**Comment by ymoslem** [comment]
Hello! Thanks for the report!

I removed `standardize=True` in the current code. If you want to use it, you can follow the instructions [here](https://github.com/jitsi/jiwer/issues/85#issuecomment-1915271530).

Currently, it is recommended to use **_SacreBLEU_** for evaluation: https://github.com/mjpost/sacrebleu
